"""initial schema

Revision ID: 0596fb81f17c
Revises: 
Create Date: 2026-06-02 14:03:05.390482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0596fb81f17c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaktionen',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('waehrung', sa.String(length=3), nullable=False),
    sa.Column('verwendungszweck', sa.String(length=500), nullable=False),
    sa.Column('gegenkonto_name', sa.String(length=200), nullable=True),
    sa.Column('gegenkonto_iban', sa.String(length=34), nullable=True),
    sa.Column('quelle', sa.String(length=20), nullable=False),
    sa.Column('rohtext', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaktionen')
    # ### end Alembic commands ###
