"""add geprueft_von to buchungssaetze

Revision ID: 74fdd3763a92
Revises: c093009470ca
Create Date: 2026-06-02 17:44:30.528120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74fdd3763a92'
down_revision: Union[str, Sequence[str], None] = 'c093009470ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buchungssaetze', sa.Column('geprueft_von', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buchungssaetze', 'geprueft_von')
    # ### end Alembic commands ###
