"""add buchungssaetze

Revision ID: c093009470ca
Revises: 0596fb81f17c
Create Date: 2026-06-02 14:13:27.107450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c093009470ca'
down_revision: Union[str, Sequence[str], None] = '0596fb81f17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buchungssaetze',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transaktion_id', sa.String(length=36), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('soll_konto', sa.String(length=10), nullable=False),
    sa.Column('haben_konto', sa.String(length=10), nullable=False),
    sa.Column('betrag_netto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('steuer_schluessel', sa.Integer(), nullable=True),
    sa.Column('steuer_betrag', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('buchungstext', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buchungssaetze')
    # ### end Alembic commands ###
